# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: DS_POSTGRESQL
    type: postgres
    access: proxy
    url: db:5432
    database: test
    user: postgres
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: 'disable'
      database: test