{
 "title": "Taxi Duration Prediction",
 "time": { "from": "2024-03-01T07:00:00.000Z", "to": "2024-04-01T05:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "DS_POSTGRESQL", "label": "PostgreSQL", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Max of Median Fare Amount (per day) for March 2024",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(median_fare_amount) FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns for March 2024",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift for March 2024",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}